CREATE TABLE TGT_ORGANISATION (ID VARCHAR PRIMARY KEY, NAME VARCHAR, FORM_CODE INT);
CREATE TABLE TGT_PERSON (ID VARCHAR PRIMARY KEY, LAST_NAME VARCHAR, FIRST_NAME VARCHAR, ORG_ID VARCHAR);
CREATE TABLE TGT_EVENT (ID VARCHAR PRIMARY KEY, TITLE VARCHAR, PLACE VARCHAR, EVENT_DATE VARCHAR);
CREATE TABLE TGT_COMMENT (COMMENT_ID VARCHAR PRIMARY KEY, EVENT_ID VARCHAR, STRUCT_CODE INT, TYPE_CODE INT, TEXT_VALUE VARCHAR, BY_ORG VARCHAR);
