package guru.interlis.convconf.plan;

import guru.interlis.convconf.lm.LmModel;

import java.util.List;

/**
 * Serializable conversion plan derived from KM + source LM + target LM.
 *
 * @param kmModel KM model identifier used to build the plan
 * @param sourceLm source LM name
 * @param targetLm target LM name
 * @param sourceModel parsed source LM model
 * @param targetModel parsed target LM model
 * @param steps linearized read/write steps generated by the planner
 */
public record ConversionPlan(String kmModel,
                             String sourceLm,
                             String targetLm,
                             LmModel sourceModel,
                             LmModel targetModel,
                             List<PlanStep> steps) {

    /**
     * Single execution step in the generated plan.
     *
     * @param phase step phase, e.g. READ or WRITE
     * @param source source name for the phase
     * @param target target name for the phase
     * @param detail free-form detail to make the plan human-readable
     */
    public record PlanStep(String phase, String source, String target, String detail) {}
}
